"use client";
// Trip planning page - left panel form + right panel results with map

import { useState, useEffect, useRef } from "react";
import { useSearchParams } from "next/navigation";
import PlanningForm from "./components/PlanningForm";
import TripResults from "./components/TripResults";
import dynamic from "next/dynamic";
import { Dancing_Script } from 'next/font/google';
import useGenerateTrip from "./useGenerateTrip";

const dancingScript = Dancing_Script({ weight: '600', subsets: ['latin'] });
// Lazy-load TripMap to avoid SSR issues with Leaflet
const TripMap = dynamic(() => import("@/components/TripMap"), { ssr: false });

export default function PlanningPage() {
    // Form input state
    const [location, setLocation] = useState("");
    const [tripType, setTripType] = useState("trek");
    const [days, setDays] = useState(1);

    const searchParams = useSearchParams();
    // Prevents auto-generation from firing more than once on re-renders
    const hasAutoGenerated = useRef(false);

    // Trip generation state and actions from custom hook
    const {
        loading, result, resultTripType, error, hasGenerated,
        routeDistances, weather, image, saved,
        generateTrip, handleApprove, handleGeometryLoaded,
    } = useGenerateTrip();

    // Auto-generate if redirected from home page with params
    useEffect(() => {
        if (hasAutoGenerated.current) return;
        const paramLocation = searchParams.get("location");
        const paramTripType = searchParams.get("tripType");
        const paramDays = searchParams.get("days");

        if (paramLocation) {
            hasAutoGenerated.current = true;
            setLocation(paramLocation);
            setTripType(paramTripType || "trek");
            setDays(Number(paramDays) || 1);
            // Trigger generation after state updates
            setTimeout(() => {
                generateTrip(paramLocation, paramTripType || "trek", Number(paramDays) || 1);
            }, 0);
        }
    }, [searchParams]);

    // Form submit handler - uses current form state
    function handleSubmit(e) {
        e.preventDefault();
        generateTrip(location, tripType, days);
    }

    return (
        // Page wrapper with diagonal stripe background pattern
        <div style={{
            backgroundColor: '#000000',
            backgroundImage: `linear-gradient(45deg,
                transparent 5%, rgba(255,255,255,0.9) 5%, rgba(255,255,255,0.9) 5.8%,
                transparent 5.8%, transparent 14%, rgba(255, 255, 255, 0.83) 14%, rgba(255,255,255,0.83) 14.3%,
                transparent 14.3%, transparent 24%, rgba(255,255,255,0.83) 24%, rgba(255,255,255,0.83) 25.2%,
                transparent 25.2%, transparent 33%, rgba(255,255,255,0.83) 33%, rgba(255,255,255,0.83) 33.4%,
                transparent 33.4%, transparent 42%, rgba(255,255,255,0.83) 42%, rgba(255,255,255,0.83) 43.1%,
                transparent 43.1%, transparent 51%, rgba(255,255,255,0.83) 51%, rgba(255,255,255,0.83) 51.5%,
                transparent 51.5%, transparent 60%, rgba(255,255,255,0.83) 60%, rgba(255,255,255,0.83) 61.9%,
                transparent 61.9%, transparent 69%, rgba(255,255,255,0.83) 69%, rgba(255,255,255,0.83) 69.3%,
                transparent 69.3%, transparent 78%, rgba(255,255,255,0.83) 78%, rgba(255,255,255,0.83) 79.5%,
                transparent 79.5%, transparent 87%, rgba(255,255,255,0.83) 87%, rgba(255,255,255,0.83) 87.2%,
                transparent 87.2%, transparent 90%, rgba(255,255,255,0.83) 90%, rgba(255,255,255,0.83) 90.7%,
                transparent 90.7%
            )`,
            minHeight: '100vh',
        }}>
            {/* Two-column layout: form on left, results on right */}
            <div style={{
                left: '0.04%',
                right: '0.04%',
                bottom: '0.09%',
                display: 'flex',
                paddingTop: '2.13vw',
            }}>
                {/* Left panel - Planning Form */}
                <div style={{
                    position: 'relative',
                    width: '19.57%',
                    minHeight: '100vh',
                    marginLeft: '0.78vw',
                    backgroundColor: '#1A1A1A',
                    overflow: 'hidden',
                }}>
                    <h1 className={`${dancingScript.className} text-center text-white`} style={{ fontSize: '1.88vw', letterSpacing: '0.31vw', marginTop: '3.13vw', padding: '0.31vw 0' }}>Plan your trip</h1>
                    <PlanningForm {...{ location, setLocation, tripType, setTripType, days, setDays, loading }} onSubmit={handleSubmit} />
                </div>

                {/* Right panel - Results area */}
                <div style={{
                    flex: 1,
                    minHeight: 'calc(100vh - 3.13vw)',
                    position: 'relative',
                    backgroundColor: 'transparent',
                }}>
                    {/* Placeholder message before first generation */}
                    {!hasGenerated && (
                        <div className="flex items-center justify-center h-full" style={{ paddingBottom: '15.63vw' }}>
                            <p className="font-bold text-orange-500" style={{ fontSize: '2.34vw' }}>Let's get started, generate a trip!</p>
                        </div>
                    )}
                    {/* Error message with retry prompt */}
                    {error && (
                        <div className="flex flex-col items-center justify-center h-full" style={{ paddingBottom: '15.63vw' }}>
                            <p className="font-bold text-red-500" style={{ fontSize: '1.5vw' }}>{error}</p>
                            <p style={{ fontSize: '0.9vw', marginTop: '0.5vw', color: '#8e8fd3ec' }}>Please try generating again.</p>
                        </div>
                    )}
                    {/* Generated results: trip details on the left, map on the right */}
                    {result && (
                        <div className="flex items-start w-full" style={{ padding: '1.25vw', gap: '0.40vw' }}>
                            <div className="min-w-0" style={{ width: '42.97vw' }}>
                                <TripResults {...{ result, resultTripType, image, weather, saved, routeDistances }} onApprove={() => handleApprove(location, tripType)} />
                            </div>
                            {/* Leaflet map - reports geometry and distances back via onGeometryLoaded */}
                            <div style={{
                                width: '31.25vw',
                                minWidth: '23.44vw',
                                height: '31.25vw',
                                marginTop: '0.60vw',
                                borderRadius: '1.25vw',
                                overflow: 'hidden',
                                border: '0.12vw solid hsl(0, 20%, 98%)',
                                boxShadow: '0px 0.12vw 0.98vw rgba(0, 0, 0, 0.35)',
                                zIndex: 10,
                            }}>
                                <TripMap
                                    routes={result.routes}
                                    tripType={resultTripType}
                                    onGeometryLoaded={handleGeometryLoaded}
                                />
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}